article_index:
    path: /article
    controller: App\Controller\ArticleController::index

article_show:
    path: /article/{id}
    controller: App\Controller\ArticleController::show
    requirements:
        id: \d+

article_new:
    path: /article/new
    controller: App\Controller\ArticleController::new

article_edit:
    path: /article/{id}/edit
    controller: App\Controller\ArticleController::edit
    requirements:
        id: \d+

article_delete:
    path: /article/{id}/delete
    controller: App\Controller\ArticleController::delete
    requirements:
        id: \d+